acacia/acacia/data/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic.list import ListView
from acacia.data.models import Project
from acacia.data.views import DatasourceDetailView, DatasourceAsZip, DatasourceAsCsv, ProjectDetailView, ProjectLocatieDetailView, \
    MeetLocatieDetailView, MeetlocatieAsZip, SeriesAsCsv, SeriesToJson, ChartToJson, GridToJson, ChartAsCsv, UpdateMeetlocatie, ChartView, \
    ChartBaseView, DashView, TabGroupView, SeriesView, GridBaseView, GridView, UpdateDatasource, StartUpdateDatasource, poll_state, get_key, get_keys

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(model=Project), name='project-list'),
    url(r'^/$', ListView.as_view(model=Project), name='project-list'),
    url(r'^bron/(?P<pk>\d+)/$', DatasourceDetailView.as_view(), name='datasource-detail'),

    url(r'^key/(?P<pk>\d+)/$', get_key, name='get_key'),
    url(r'^keys/$', get_keys, name='get_keys'),
    url(r'^download/datasource/(?P<pk>\d+)', DatasourceAsZip,name='datasource-zip'),
    url(r'^download/tabel/(?P<pk>\d+)', DatasourceAsCsv,name='datasource-csv'),
    url(r'^download/meetlocatie/(?P<pk>\d+)', MeetlocatieAsZip,name='meetlocatie-zip'),
    url(r'^download/reeks/(?P<pk>\d+)', SeriesAsCsv,name='series-csv'),
    url(r'^download/grafiek/(?P<pk>\d+)', ChartAsCsv,name='chart-csv'),
    
    url(r'^update/(?P<pk>\d+)',UpdateDatasource,name='datasource-update'),
    url(r'^update/meetlocatie/(?P<pk>\d+)', UpdateMeetlocatie,name='meetlocatie-update'),
    
    url(r'^start/(?P<pk>\d+)',StartUpdateDatasource,name='start-datasource-update'),
    url(r'^start/poll_state$', poll_state, name="poll_state"),
        
    url(r'^get/series/(?P<pk>\d+)/$', SeriesToJson),
    url(r'^get/chart/(?P<pk>\d+)/$', ChartToJson),
    url(r'^get/grid/(?P<pk>\d+)/$', GridToJson),
    
    url(r'^series/(?P<pk>\d+)/$', SeriesView.as_view(), name='series-detail'),
    url(r'^chart/(?P<pk>\d+)/$', ChartBaseView.as_view(), name='chart-detail'),
    url(r'^grid/(?P<pk>\d+)$', GridBaseView.as_view(), name='grid-detail'),
    url(r'^grafiek/(?P<pk>\d+)/$', ChartView.as_view(), name='chart-view'),
    url(r'^profiel/(?P<pk>\d+)$', GridView.as_view(), name='grid-view'),
    url(r'^dashboard/(?P<pk>\d+)/$', DashView.as_view(), name='dash-view'),
    url(r'^tabs/(?P<pk>\d+)/$', TabGroupView.as_view(), name='tabgroup'),
    url(r'^project/(?P<pk>\d+)/$', ProjectDetailView.as_view(), name='project-detail'),
    url(r'^locatie/(?P<pk>\d+)$', ProjectLocatieDetailView.as_view(), name='projectlocatie-detail'),
    url(r'^meetlocatie/(?P<pk>\d+)$', MeetLocatieDetailView.as_view(), name='meetlocatie-detail'),
    
    url(r'^chaining/', include('smart_selects.urls'))
)

acacia/acacia/meetnet/urls.py
from django.conf.urls import patterns, url
from .views import NetworkView, WellView, ScreenView, WellChartView

urlpatterns = patterns('acacia.meetnet.views',
    url(r'^$', NetworkView.as_view(), name='home'),
    url(r'^(?P<pk>\d+)$', NetworkView.as_view(), name='network-detail'),
    url(r'^well/(?P<pk>\d+)$', WellView.as_view(), name='well-detail'),
    url(r'^screen/(?P<pk>\d+)$', ScreenView.as_view(), name='screen-detail'),
    url(r'^chart/(?P<pk>\d+)/$', WellChartView.as_view(), name='chart-detail'),
    url(r'^info/(?P<pk>\d+)/$', 'wellinfo', name='well-info'),
)

acacia/acacia/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'acacia.views.home', name='home'),
    url(r'^cam/(?P<how>\w+)?$', 'acacia.views.cam', name='cam'),
    url(r'^mail$', 'acacia.views.mail'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^knmi/', include('acacia.data.knmi.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^data/', include('acacia.data.urls',namespace='acacia')),
    #url(r'^spaarwater/', include('spaarwater.urls')),
    url(r'^spaarwater/', 'acacia.views.spaarwater'),
)

from django.contrib.auth import views as auth_views
urlpatterns += patterns('',
    url(r'^password/change/$',
                    auth_views.password_change,
                    name='password_change'),
    url(r'^password/change/done/$',
                    auth_views.password_change_done,
                    name='password_change_done'),
    url(r'^password/reset/$',
                    auth_views.password_reset,
                    name='password_reset'),
    url(r'^accounts/password/reset/done/$',
                    auth_views.password_reset_done,
                    name='password_reset_done'),
    url(r'^password/reset/complete/$',
                    auth_views.password_reset_complete,
                    name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                    auth_views.password_reset_confirm,
                    name='password_reset_confirm'),
    url(r'^accounts/', include('registration.backends.default.urls'))    
)
 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

acacia/acacia/meetnet/models.py
'''
Created on Jun 1, 2014

@author: theo
'''
import os, pandas as pd, numpy as np
from django.db import models
from django.contrib.gis.db import models as geo
from django.core.urlresolvers import reverse
from acacia.data.models import MeetLocatie, Datasource, Series, SourceFile
from acacia.data import util

class Network(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name = 'naam')
    logo = models.ImageField(upload_to='logos')
    homepage = models.URLField(blank=True, help_text = 'website van meetnetbeheerder')
    bound = models.URLField(blank=True,verbose_name = 'grens', help_text = 'url van kml file met begrenzing van het meetnet')
    last_round = models.DateField(null=True,blank=True,verbose_name = 'laatste uitleesronde')
    next_round = models.DateField(null=True,blank=True,verbose_name = 'volgende uitleesronde')
    
    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('network-detail', args=[self.id])

    class Meta:
        verbose_name = 'netwerk'
        verbose_name_plural = 'netwerken'

class Well(geo.Model):
    network = models.ForeignKey(Network, verbose_name = 'Meetnet')
    name = models.CharField(max_length=50, unique=True, verbose_name = 'naam')
    nitg = models.CharField(max_length=50, verbose_name = 'TNO/NITG nummer', blank=True)
    bro = models.CharField(max_length=50, verbose_name = 'BRO nummer', blank=True)
    location = geo.PointField(srid=28992,verbose_name='locatie',help_text='locatie in rijksdriehoeksstelsel coordinaten')
    description = models.TextField(verbose_name='locatieomschrijving',blank=True)
    maaiveld = models.FloatField(null=True, blank=True, verbose_name = 'maaiveld', help_text = 'maaiveld in meter tov NAP')
    date = models.DateField(null=True, blank=True, verbose_name = 'constructiedatum')
    straat = models.CharField(max_length=60, blank=True)
    huisnummer = models.CharField(max_length=6, blank=True)
    postcode = models.CharField(max_length=8, blank=True)
    plaats = models.CharField(max_length=60, blank=True)
    log = models.ImageField(null=True,blank=True,upload_to='logs',verbose_name = 'boorstaat')
    chart = models.ImageField(null=True,blank=True, upload_to='charts', verbose_name='grafiek')
    g = models.FloatField(default=9.80665,verbose_name='valversnelling', help_text='valversnelling in m/s2')
    objects = geo.GeoManager()

    def latlon(self):
        return util.toWGS84(self.location)

    def RD(self):
        return util.toRD(self.location)

    def num_filters(self):
        return self.screen_set.count()
    num_filters.short_description='aantal filters'

    def num_photos(self):
        return self.photo_set.count()
    num_photos.short_description='aantal fotos'

#     def get_loggers(self):
#         loggers = []
#         for s in self.screen_set.all():
#             loggers.extend(s.datalogger_set.all())
#         return loggers
#     
#     def num_loggers(self):
#         return len(self.get_loggers())
#     num_loggers.short_description='aantal dataloggers'
#     
#     def logger_names(self):
#         return ','.join([l.serial for l in self.get_loggers()])
#     logger_names.short_description='dataloggers'
    
    def get_absolute_url(self):
        return reverse('well-detail', args=[self.id])

    def __unicode__(self):
        return self.name
    
    def has_data(self):
        for s in self.screen_set.all():
            if s.has_data():
                return True
        return False
    
    class Meta:
        verbose_name = 'put'
        verbose_name_plural = 'putten'
        ordering = ['name',]

class Photo(models.Model): 
    well = models.ForeignKey(Well)
    photo = models.ImageField(upload_to = 'fotos') 
    
    def thumb(self):
        url = self.photo.url
        return '<a href="%s"><img src="%s" height="60px"/></a>' % (url,url)

    def __unicode__(self):
        return os.path.basename(self.photo.file.name)

    thumb.allow_tags=True
    thumb.short_description='voorbeeld'

    class Meta:
        verbose_name = 'foto'
        verbose_name_plural = "foto's"
    
MATERIALS = (
             ('pvc', 'PVC'),
             ('hdpe', 'HDPE'),
             ('ss', 'RVS'),
             ('ms', 'Staal'),
             )                  
class Screen(models.Model):
    well = models.ForeignKey(Well, verbose_name = 'put')
    nr = models.IntegerField(default=1, verbose_name = 'filternummer')
    density = models.FloatField(default=1000.0,verbose_name='dichtheid',help_text='dichtheid van het water in de peilbuis in kg/m3')
    refpnt = models.FloatField(null=True, blank=True, verbose_name = 'bovenkant buis', help_text = 'bovenkant peilbuis in meter tov NAP')
    top = models.FloatField(null=True, blank=True, verbose_name = 'bovenkant filter', help_text = 'bovenkant filter in meter min maaiveld')
    bottom = models.FloatField(null=True, blank=True, verbose_name = 'onderkant filter', help_text = 'onderkant filter in meter min maaiveld')
    diameter = models.FloatField(null=True, blank=True, verbose_name = 'diameter buis', default=32, help_text='diameter in mm (standaard = 32 mm)')
    material = models.CharField(blank=True, max_length = 10,verbose_name = 'materiaal', default='pvc', choices = MATERIALS)
    chart = models.ImageField(null=True,blank=True, upload_to='charts', verbose_name='grafiek')

    def get_series(self, ref = 'nap', kind='COMP'):
        
        def bydate(record):
            return record[0]

        levels = []
        # luchtdruk gecompenseerde standen (tov NAP) ophalen
        name = '%s %s' % (unicode(self), kind)
        try:
            series = Series.objects.get(name=name)
        except Series.DoesNotExist:
            return levels
        for dp in series.datapoints.all():
            try:
                if ref == 'nap':
                    level = dp.value
                elif ref == 'bkb':
                    level = self.refpnt - dp.value
                elif ref == 'mv':
                    level = self.well.maaiveld - dp.value
                else:
                    raise 'Illegal reference for screen %s' % unicode(self)
                levels.append((dp.date, level))
            except:
                pass # refpnt, maaiveld or value is None
        levels.sort(key=bydate)
        return levels

    def get_levels(self, ref='nap'):
        return self.get_series(ref,kind='COMP')        

    def get_hand(self, ref='nap'):
        return self.get_series(ref,kind='HAND')        
        
    def get_monfiles(self):
        files = []
        for lp in self.loggerpos_set.all():
            files.extend(lp.monfile_set.all())
        return files

    def num_files(self):
        files = self.get_monfiles()
        return len(files)
    
    def num_standen(self):
        files = self.get_monfiles()
        return sum([f.rows for f in files]) if len(files)> 0 else 0

    def has_data(self):
        return self.num_standen() > 0

    def start(self):
        files = self.get_monfiles()
        return min([f.start for f in files]) if len(files) > 0 else None

    def stop(self):
        files = self.get_monfiles()
        return max([f.stop for f in files]) if len(files) > 0 else None
        
    def get_loggers(self):
        return [p.logger for p in self.loggerpos_set.all().group_by('logger').last()]
        
    def last_logger(self):
        last = self.loggerpos_set.all().order_by('start_date').last()
        return last
        
    def __unicode__(self):
        return '%s/%03d' % (self.well.nitg, self.nr)
        #return '%s/%03d' % (self.well, self.nr)

    def get_absolute_url(self):
        return reverse('screen-detail', args=[self.id])

    def to_pandas(self, ref='nap',kind='COMP'):
        levels = self.get_series(ref,kind)
        if len(levels) > 0:
            x,y = zip(*levels)
        else:
            x = []
            y = []
        return pd.Series(index=x, data=y, name=unicode(self))
        
    def stats(self):
        df = self.to_pandas()
        s = df.describe(percentiles=[.1,.5,.9])
        s['p10'] = None if np.isnan(s['10%']) else s['10%']
        s['p50'] = None if np.isnan(s['50%']) else s['50%']
        s['p90'] = None if np.isnan(s['90%']) else s['90%']
        return s
        
    class Meta:
        unique_together = ('well', 'nr',)
        verbose_name = 'filter'
        verbose_name_plural = 'filters'
        ordering = ['well', 'nr',]
        
DIVER_TYPES = (
               ('micro','Micro-Diver'),
               ('3', 'TD-Diver'),
               ('ctd','CTD-Diver'),
               ('16','Cera-Diver'),
               ('14','Mini-Diver'),
               ('baro','Baro-Diver')
               )
class Datalogger(models.Model):
    serial = models.CharField(max_length=50,verbose_name = 'serienummer',unique=True)
    model = models.CharField(max_length=50,verbose_name = 'type', default='14', choices=DIVER_TYPES)

    def __unicode__(self):
        return self.serial
 
    class Meta:
        ordering = ['serial']

class LoggerPos(models.Model):
    logger = models.ForeignKey(Datalogger)
    screen = models.ForeignKey(Screen,verbose_name = 'filter',blank=True, null=True)
    start_date = models.DateTimeField(verbose_name = 'start', help_text = 'Tijdstip van start datalogger')   
    end_date = models.DateTimeField(verbose_name = 'stop', blank=True, null=True, help_text = 'Tijdstrip van stoppen datalogger')   
    refpnt = models.FloatField(verbose_name = 'referentiepunt', blank=True, null=True, help_text = 'ophangpunt in meter tov NAP')
    depth = models.FloatField(verbose_name = 'kabellengte', blank=True, null=True, help_text = 'lengte van ophangkabel in meter')
    baro = models.ForeignKey(Series, blank=True, null=True, verbose_name='luchtdruk', help_text = 'tijdreeks voor luchtdruk compensatie')
    remarks = models.TextField(verbose_name='opmerkingen', blank=True) 

    def __unicode__(self):
        return '%s@%s' % (self.logger, self.screen)

acacia/acacia/meetnet/templates/meetnet/chart_detail.html
{% extends 'highchart.html' %}
{% block title %}Grafiek {{object}}{% endblock title %}
{% block content %}
{{ block.super }}
{% endblock %}

acacia/acacia/meetnet/templates/meetnet/network_detail.html
{% extends 'bootbase.html' %}
{% load staticfiles %}
{% load l10n %}
{% block title %}Grondwatermeetnet {{object.name}} {% endblock title %}
{% block breadcrumbs %}{% endblock %}
{% block extrastyle %}
<style type="text/css">
	.labels {
		color: black;
		background-color: #FFFF66;
		font-family: "Lucida Grande", "Arial", sans-serif;
		font-size: 10px;
		font-weight: bold;
		text-align: center;
		width: 54px;     
		border: none;
		white-space: nowrap;
/* 		text-shadow: 0px 0px 12px red; */
	}
	.nolabels {
	    display: none; 
	}
	.scroll {
		overflow-y: auto;
		max-height: 800px;
	}
 </style>
{% endblock %}
{% block brandname %}<div class="navbar-brand"><a href="{{object.homepage}}"><img style="margin-top: -7px;max-width: 100px;" src="/media/{{object.logo}}"/></a> Grondwatermeetnet {{object.name}}</div>{% endblock %}
{% block script %}
{{ block.super }}
{% localize off %}
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="{% static "js/markerwithlabel.js" %}"></script>
<script>
var map;
var markers;

function initialize() {
    map = new google.maps.Map(document.getElementById('map'), {
        zoom: 14,
        mapTypeId: google.maps.MapTypeId.{{maptype}}
    });
	var json = {{content|safe}};
	var bounds = new google.maps.LatLngBounds();
	var infowindow = new google.maps.InfoWindow();
	var marker;
	markers = new Array();
	json.forEach(function(loc) {
			marker = new MarkerWithLabel({
			icon: {
			      path: google.maps.SymbolPath.CIRCLE,
			      scale: 6,
			      fillColor: 'red',
			      fillOpacity: 0.8,
			      strokeColor: 'white',
			      strokeWeight: 2
			},
   			position: new google.maps.LatLng(loc.lat,loc.lon),
			title: loc.name, 
   			map: map,
   			labelContent: loc.name,
   	        labelAnchor: new google.maps.Point(27, -10),
   	        labelClass: 'labels',
   	        labelStyle: {'opacity': 0.8},
   	        labelInBackground: true,
   	        labelVisible: false
   		});
   		markers.push(marker);
   		google.maps.event.addListener(marker, 'click', (function(marker) {
	        return function() {
                //infowindow.setContent('Loading data...');  
                //infowindow.open(map, marker);  
	            $.ajax({  
	                url: loc.url,  
	                success: function(data) {  
	                    infowindow.setContent(data);  
	                    infowindow.open(map, marker);  
	                }  
	            });  
	        }
	      })(marker));
		bounds.extend(marker.position);
	});
	{% if boundary %}
		var grens = new google.maps.KmlLayer({ url: '{{boundary}}', map: map});	
	{% else %}
		map.fitBounds(bounds);
	{% endif %}
}

$(function(){
	initialize();
	$('#hidelabels').hide();
	});

function showMarker(m) {
	markers[m].setAnimation(google.maps.Animation.BOUNCE);	
}
function hideMarker(m) {
	markers[m].setAnimation(null);	
}

function showLabels() {
	var len = markers.length;
	for(var i=0; i< len; i++) {
		m = markers[i];
		m.set("labelVisible", true);
	}
	$('#showlabels').hide();
	$('#hidelabels').show();
}

function hideLabels() {
	var len = markers.length;
	for(var i=0; i< len; i++) {
		m = markers[i];
		m.set("labelVisible", false);
	}
	$('#showlabels').show();
	$('#hidelabels').hide();
}

</script>
{% endlocalize %}
{% endblock %}
{% block content %}
<div class = "container-fluid">
<!--<div class = "row-fluid">
<div class = "col-md-12"><h3>Meetnet {{object.name}}</h3>{{object.description|safe}}</div>
</div>
-->
<div class = "row-fluid">
<div class = "col-md-10"><div id= map style="width:100%;height:800px;"></div>
<button class = "btn btn-primary" id="showlabels" onclick="showLabels()">Labels tonen</button>
<button class = "btn btn-primary" id="hidelabels" onclick="hideLabels()">Labels verbergen</button>
<button class = "btn" id="uploadMon" onclick="uploadMonfile()">Upload</button>
</div>
<div class = "col-md-2">
<div class = "list-group scroll">
<a class="list-group-item active" data-toggle="collapse" data-target="#putten" aria-expanded="true" aria-controls="putten">Putten<span class="badge">{{object.well_set.count}}</a>
<div class="collapse in" id="putten">
{% for well in object.well_set.all %}
<a onmouseover="showMarker({{forloop.counter0}});" onmouseout="hideMarker({{forloop.counter0}});" href="{% url 'well-detail' well.id %}" class="list-group-item">{{well.name}}
{% if well.straat %}<br/><div class='text-muted'><small>{{well.straat}}, {{well.plaats}}</small></div>{% endif %}</a>
{% endfor %}
</div>
</div>
</div>
</div>
{% endblock content %}

acacia/acacia/meetnet/templates/meetnet/plain_chart.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 	<link href="{% static "img/favicon.ico" %}" rel="icon" type="image/x-ico" />
	<title>Grafiek {{object}}</title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="http://code.highcharts.com/stock/highstock.js"></script>
	<script src="http://code.highcharts.com/highcharts-more.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- 	<script src="http://code.highcharts.com/highcharts.js"></script> -->
	<script src="{% static 'themes/gray.js' %}"></script>
	<script src="{% static 'js/nl.js' %}"></script>
	<script>
		$(function () {
		  $('#container').highcharts({{ options|safe }});
		});
	</script>
	<style>
	html, body {height:100%;margin:0;padding:0;}
	</style>
</head>
<body>
<div id="container" style="height:80%;"></div>
<!-- <<div class="text-center"> -->
<!-- <a href="{% url 'acacia:series-csv' series.id %}" class="btn btn-primary active" data-toggle="tooltip" title="Tijdreeks downloaden als csv bestand" id="download">Downloaden</a> -->
<!-- </div> -->
</body>
</html>

acacia/acacia/meetnet/templates/meetnet/screen_detail.html
{% extends 'bootbase.html' %}
{% block title %}Filter {{object.name}} {% endblock title %}
{% block content %}
<img src="{{chart}}"/>
{% endblock content %}

acacia/acacia/meetnet/templates/meetnet/well_detail.html
{% extends 'bootbase.html' %}
{% block title %}Grondwaterput {{object.name}} {% endblock title %}
{% block breadcrumbs %}
<ol class="breadcrumb">
  <li><a href="{% url 'network-detail' object.network.id %}">Netwerk</a></li>
</ol>
{% endblock breadcrumbs %}
{% block brandname %}<div class="navbar-brand"><img style="margin-top: -7px;max-width: 100px;" src="/media/{{object.network.logo}}"/></div>{% endblock %}
{% block extrastyle %}
<style>
html, body {height: 100%;margin:0;padding:0;}
a img {
	float: left;
	height: 474px;
	padding-right: 8px;
}
.log {
	float:right;
	padding-left: 0;
	height: 474px;
}
.grafiek {
	width: 100%;
	height: 30%;
}
.grafiek img {
	width: 100%;
	height: 100%;
}

</style>
{% endblock %}
{% block content %}
<div id="content">
<div class="container-fluid">
<h4>Grondwaterput {{object.name}}</h4>
<table class="table table-striped">
<tr>
	<td class="col-md-2">NITG code</td>
	<td class="col-md-10">{{object.nitg|default:'<i>geen</i>'}}</td>
	{% if object.log %}
	<td rowspan="10"><a href="/media/{{object.log}}"><img class="log" src="/media/{{object.log}}"/></a></td>
	{% endif %}
</tr>
<tr><td>BRO id</td><td>{{object.bro|default:'<i>onbekend</i>'}}</td></tr>
<tr>
	<td>Adres</td>
	<td>{%if object.straat %} {{object.straat}} {{object.huisnummer}}{%else%}<i>onbekend</i>{%endif%}</td>
</tr>
<tr><td>Plaats</td><td>{%if object.plaats %}{{object.postcode}} {{object.plaats}}{%else%}<i>onbekend</i>{%endif%}</td></tr>
<tr><td>Coördinaten</div></td><td>({{object.RD.x|floatformat:2}}&nbsp;{{object.RD.y|floatformat:2}})</td></tr>
<tr><td>Constructiedatum</div></td><td>{% if object.date %}{{object.date}}{%else%}<i>onbekend</i>{%endif%}</td></tr>
<tr><td>Maaiveld</div></td><td>{%if object.maaiveld %}{{object.maaiveld|floatformat:2}} m NAP{%else%}<i>onbekend</i>{%endif%}</td></tr>
<tr><td>Filters</td><td>{{object.num_filters}}</td></tr>
<tr><td>Laatste uitleesronde</td><td>{{object.network.last_round|default:'<i>onbekend</i>'}}</td></tr>
<tr>
<td>{%for f in object.photo_set.all %}<a href="/media/{{f.photo.name}}"><img src="/media/{{f.photo.name}}"/></a>{%endfor%}</td>
<td>
{% if object.has_data %}
<div class="grafiek">
	<a href="{% url 'chart-detail' object.id %}" target="_blank">
		<img src="{{chart}}" alt='grafiek' title='Klik voor interactieve grafiek in aparte tab'/>
	</a>
</div>
{% endif %}
<table class="table table-bordered table-striped">
<thead>
<tr>
	<th rowspan="2">Filter</th>
	<th colspan="2"><div class = "text-center">Datalogger</div></th>
	<th colspan="2"><div class = "text-center">Filterstelling (m tov maaiveld)</div></th>
	<th colspan="6"><div class = "text-center">Standen (m tov NAP)</div></th>
</tr>
<tr>
	<th>Serienummer</th>
	<th>Diepte</th>
	<th>Bovenkant</th>
	<th>Onderkant</th>
	<th>Van</th>
	<th>Tot</th>
	<th>Aantal</th>
	<th>10%</th>
	<th>50%</th>
	<th>90%</th>
</tr>
</thead>
<tbody>
    {% for s in object.screen_set.all %}
	<tr>
    {% with s.stats as stats %}
		<td>{{s.nr}}</td>
		<td>{{s.last_logger.logger|default:''}}</td>
		<td>{{s.last_logger.depth}}</td>
		<td>{{s.top}}</td>
		<td>{{s.bottom}}</td>
		<td>{{s.start|date:'d M Y'}}</td>
		<td>{{s.stop|date:'d M Y'}}</td>
		<td>{{s.num_standen}}</td>
		<td>{{stats.p10|default:''}}</td>
		<td>{{stats.p50|default:''}}</td>
		<td>{{stats.p90|default:''}}</td>
	{% endwith %}
	</tr>
    {% endfor %} 
</tbody>
</table>
</td>
</tr>
</table>
</div>
</div>
{% endblock content %}